---
apiVersion: v1
kind: Service
metadata:
  name: cnat-web-app-svc
  namespace: cnat
spec:
  type: NodePort
  selector:
    app: cnat-web-app
  ports:
    - port: 30083
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnat-web-app-deploy
  namespace: cnat
  labels:
    app: cnat-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cnat-web-app
  template:
    metadata:
      labels:
        app: cnat-web-app
    spec:
      containers:
        - name: some-cnat-web-app
          image: cnat-web-app
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
              ephemeral-storage: 100Mi
            limits:
              memory: 512Mi
              cpu: 250m
              ephemeral-storage: 100Mi
